import type { TicketItem, TripDocument } from "./tripcard";
import type { LocalFinding } from "./tripAudit";
const ENDPOINT = "https://openrouter.ai/api/v1/chat/completions"; const TRANSIENT = new Set([408, 429, 500, 502, 503, 504]);
export class OpenRouterError extends Error { constructor(public kind: "missing-key" | "invalid-key" | "overloaded" | "network" | "invalid-response", message: string) { super(message); this.name = "OpenRouterError"; } }
const extractJson = (content: string) => { const fenced = content.match(/```(?:json)?\s*([\s\S]*?)\s*```/i)?.[1] ?? content; const start = fenced.indexOf("{"); const end = fenced.lastIndexOf("}"); return JSON.parse(start >= 0 && end > start ? fenced.slice(start, end + 1) : fenced); };
async function callJson<T>(apiKey: string, model: string, system: string, user: unknown, maxRetries = 1): Promise<T> { if (!apiKey.trim()) throw new OpenRouterError("missing-key", "Renseigne une clé OpenRouter locale."); for (let attempt = 0; attempt <= maxRetries; attempt += 1) { if (attempt) await new Promise(resolve => setTimeout(resolve, Math.min(12000, 800 * 2 ** (attempt - 1)))); try { const response = await fetch(ENDPOINT, { method: "POST", headers: { "Content-Type": "application/json",
 Authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ model, messages: [{ role: "system", content: system }, { role: "user", content: JSON.stringify(user) }], response_format: { type: "json_object" }, temperature: 0.05, max_tokens: 7000 }) }); const payload = await response.json().catch(() => ({})) as { choices?: Array<{ message?: { content?: string } }>; error?: { message?: string } }; if (!response.ok) { if (TRANSIENT.has(response.status) && attempt < maxRetries) continue; throw new OpenRouterError(response.status === 401 || response.status === 403 ? "invalid-key" : TRANSIENT.has(response.status) ? "overloaded" : "network", payload.error?.message || `OpenRouter a répondu avec le statut ${response.status}.`); } const content = payload.choices?.[0]?.message?.content; if (!content) throw new OpenRouterError("invalid-response", "OpenRouter n’a renvoyé aucun JSON exploitable."); try { return extractJson(content) as T; } catch { throw new OpenRouterError("invalid-response", "La réponse OpenRouter n’est pas un JSON valide."); } } catch (error) { if (error instanceof OpenRouterError && (error.kind !== "network" || attempt >= maxRetries)) throw error; if (attempt >= maxRetries) throw new OpenRouterError("network", "La connexion à OpenRouter a échoué."); } } throw new OpenRouterError("network", "OpenRouter n’a pas pu être contacté."); }
const itinerarySystem = `Tu es un agent de voyage senior. Construis une seule fois l'itinéraire opérationnel jour par jour depuis les prestations fournies. Ne crée aucun événement qui ne soit pas dans les données fournies.

REGLE HEBERGEMENT : chaque hôtel doit être renseigné une seule fois dans le champ night du jour d'arrivée (title = nom de l'hôtel, location = ville/adresse, notes = période complète du séjour dans cet hôtel du type "du 18 au 20 septembre"). Ne crée JAMAIS un événement de type Hôtel répété dans le tableau events pour chaque nuit intermédiaire : les jours qui ne sont ni arrivée ni départ d'un hôtel n'ont pas besoin de mentionner l'hébergement dans events.

REGLES DE CONTENU PAR TYPE D'EVENEMENT, à respecter strictement dans les champs title/subtitle/departure/arrival/notes :
- Vol : title contient le numéro de vol et le PNR ou code de réservation s'il existe (ex "V7 2236 · G4FEKY") ; departure et arrival contiennent les heures de départ et d'arrivée ; location le trajet aéroport à aéroport ; notes la compagnie et les détails bagages pertinents.
- Activité : title est le nom exact de l'activité ; subtitle le prestataire ou guide si connu ; notes une courte description si elle existe dans le texte source.
- Transfert : title est le nom du prestataire (ex "ARFEL TAXI") ; location le trajet lieu de départ vers lieu d'arrivée ; time l'heure de prise en charge.
- Location voiture : title le nom du loueur ; subtitle indique BSP, Flexible, ou "(non précisé)" si le statut n'est pas trouvé ; reference la référence de location ; location le lieu de prise en charge.
- Ferry : même principe que Transfert (prestataire, trajet, heure).

Le titre ne doit jamais être seulement la catégorie générique de la prestation. Toutes les dates au format ISO strict YYYY-MM-DD, jamais DD/MM/YYYY ni texte libre. Donnée absente = (à vérifier), ne l'invente jamais.

detectedTypes doit couvrir obligatoirement Vol, Hôtel, Activité, Transfert, Train, Location voiture, Ferry, même à 0 occurrence : quand count vaut 0, evidence doit être une phrase complète et directement affichable au format "Aucun/Aucune [type] identifié(e) dans les données fournies", jamais une phrase vague.

Réponds uniquement en JSON avec destination, period, travelers, days, undated et detectedTypes.`;
const auditSystem = `Tu es un agent de voyage senior et controleur qualite final d un voyage haut de gamme, avant depart. Tu as l oeil d un professionnel qui a vu des centaines de dossiers et qui sait precisement ou se cachent les erreurs couteuses. L itineraire fourni est deja la base de verite de travail : ne le reconstruis pas, ne produis pas un second itineraire, ne remplace aucune prestation.

GRILLE DE DETECTION SYSTEMATIQUE, a balayer entierement pour chaque dossier :
1. Coherence temporelle : chevauchements d horaires, trous de programme sur une journee entiere, nuit sans hebergement identifie, transfert programme avant l heure d arrivee du vol associe.
2. Coherence geographique : rupture de continuite entre deux lieux consecutifs sans transport identifie, transfert vers un lieu incoherent avec l etape suivante.
3. Coherence documentaire : prestation mentionnee dans l itineraire sans voucher correspondant ou l inverse, divergence de nom, date, heure ou lieu entre voucher, roadbook et itineraire.
4. Completude par type de prestation : vol sans PNR complet, hotel sans reference de reservation, activite ou transfert avec instruction de reconfirmation mais aucun rappel prevu.
5. Coherence voyageurs : nombre de places, chambres ou sieges reserves inferieur au nombre de voyageurs declare.
6. Documents d identite : presence ou absence signalee de passeport ou CNI par voyageur, jamais de jugement sur le contenu du document lui-meme.

REGLES DE RIGUEUR IMPERATIVES :
- Ne qualifie jamais d incoherence une simple absence d information plausible mais non fournie : classe-la comme point a verifier avec l agence, pas comme anomalie.
- Ne signale un conflit que s il est objectivable et precisement citable avec les deux valeurs en cause.
- N invente jamais une anomalie pour remplir une categorie vide : un dossier propre doit produire une liste vide, pas une liste artificielle.
- Chaque mismatch doit donner la valeur de l itineraire, la valeur du voucher ou roadbook, la consequence metier concrete et la correction exacte a demander.
- Si une source est absente, cree une action obtenir la preuve plutot que de conclure que tout va bien.
- Utilise les controles locaux fournis comme indices de travail, jamais comme verite absolue a valider aveuglement.

Classe chaque resultat : red = critique, depart compromis, action immediate necessaire avec preuve a obtenir ; orange = a verifier ou action a planifier, avec responsable et echeance ; green = controle et conforme, avec preuve citee. Donne une decision globale GO, GO_WITH_CHECKS ou NO_GO. Retourne uniquement ce JSON : {"status":"stable|attention|blocking","globalDecision":"GO|GO_WITH_CHECKS|NO_GO","confidence":0,"summary":"résumé précis","redItems":[{"code":"","title":"","detail":"","action":"","evidence":"","sourceRefs":[],"affectedServiceIds":[],"proofRequired":""}],"orangeItems":[{"code":"","title":"","detail":"","action":"","evidence":"","sourceRefs":[],"affectedServiceIds":[],"owner":"","proofRequired":""}],"greenChecks":[{"code":"","title":"","detail":"","evidence":"","sourceRefs":[]}],"duplicateCandidates":[],"dataReview":[],"crossSourceComparisons":[{"title":"","itineraryValue":"","voucherValue":"","roadbookValue":"","result":"match|mismatch|missing","action":""}],"actions":[{"priority":"red|orange|green","title":"","detail":"","owner":"","proofRequired":""}],"missingEvidence":[],"localRuleResults":[]}. Français uniquement.`;
export type BuiltItinerary = { destination: string; period: string; travelers: Array<{ name: string; details?: string }>; days: Array<{ date: string; label: string; city?: string; night?: { title: string; location: string; notes: string } | null; events: Array<{ time: string; type: string; category?: string; title: string; subtitle?: string; location: string; departure?: string; arrival?: string; reference: string; notes: string; sourceRefs?: string[] }>; warnings?: string[] }>; undated: Array<{ type: string; title: string; notes: string; sourceRefs?: string[] }>; detectedTypes: Array<{ type: string; count: number; evidence: string }> };
export type AuditItem = { code: string; title: string; detail: string; action?: string; evidence?: string; sourceRefs?: string[]; affectedServiceIds?: string[]; owner?: string; proofRequired?: string; itineraryValue?: string; voucherValue?: string; roadbookValue?: string; result?: string };
export type Audit360 = { status: "stable" | "attention" | "blocking"; globalDecision: "GO" | "GO_WITH_CHECKS" | "NO_GO"; confidence: number; summary: string; description?: string; redItems: AuditItem[]; orangeItems: AuditItem[]; greenChecks: AuditItem[]; duplicateCandidates: AuditItem[]; dataReview: AuditItem[]; crossSourceComparisons: AuditItem[]; localRuleResults: AuditItem[]; missingEvidence: AuditItem[]; actions: Array<{ priority: string; title: string; detail: string; owner: string; proofRequired?: string }> };
export function buildLocalItinerary(document: TripDocument): BuiltItinerary { const byDay = document.days.map(day => ({ date: day.date, label: day.label, city: day.city, night: day.night ? { title: day.night.displayTitle, location: day.night.location, notes: day.night.notes } : null, events: day.events.map(item => ({ time: item.time, type: item.type, category: item.category, title: item.displayTitle, subtitle: item.subtitle, location: item.location, departure: item.departure, arrival: item.arrival, reference: item.reference, notes: item.notes, sourceRefs: item.sourceRefs })), warnings: day.warnings })); const dated = new Set(document.itinerary.flatMap(item => [item.id, ...item.nightCoverage])); const undated = document.itinerary.filter(item => !item.date).map(item => ({ type: item.type, title: item.displayTitle, notes: `${item.location || "Lieu à vérifier"} · ${item.notes || "Date à vérifier"}`, sourceRefs: item.sourceRefs })); return { destination: document.meta.destination, period: document.meta.period, travelers: document.meta.travelers.map(traveler => ({ name: String(traveler.name || traveler.fullName || "Voyageur") })), days: byDay, undated, detectedTypes: Array.from(new Set(document.itinerary.map(item => item.type))).map(type => ({ type, count: document.itinerary.filter(item => item.type === type).length, evidence: "Prestation normalisée depuis le JSON extension" })) }; }
function normalizeOutputDate(value: unknown) { const raw = String(value || "").trim(); const iso = raw.match(/^(20\d{2})-(\d{2})-(\d{2})/); if (iso) return `${iso[1]}-${iso[2]}-${iso[3]}`; const fr = raw.match(/^(\d{1,2})\/(\d{1,2})\/(20\d{2})$/); return fr ? `${fr[3]}-${fr[2].padStart(2, "0")}-${fr[1].padStart(2, "0")}` : ""; }
function dayLabel(date: string) { if (!date) return "Date à vérifier"; const parsed = new Date(`${date}T12:00:00Z`); return Number.isNaN(parsed.getTime()) ? "Date à vérifier" : parsed.toLocaleDateString("fr-FR", { day: "2-digit", month: "long" }); }
function normalizeBuiltItinerary(value: Partial<BuiltItinerary> | null | undefined): BuiltItinerary { const source = value || {}; const destination = String(source.destination || "Destination à vérifier"); return { destination, period: String(source.period || "Période à vérifier"), travelers: Array.isArray(source.travelers) ? source.travelers : [], days: Array.isArray(source.days) ? source.days.map(day => { const date = normalizeOutputDate(day?.date); return { ...day, date, label: date ? dayLabel(date) : String(day?.label || "Date à vérifier"), city: String(day?.city || destination), events: Array.isArray(day?.events) ? day.events : [], warnings: Array.isArray(day?.warnings) ? day.warnings : [] }; }) : [], undated: Array.isArray(source.undated) ? source.undated : [], detectedTypes: Array.isArray(source.detectedTypes) ? source.detectedTypes : [] }; }
export async function buildItinerary(apiKey: string, model: string, document: TripDocument, voucherSummary: string) { const response = await callJson<Partial<BuiltItinerary>>(apiKey, model, itinerarySystem, { dossier: document.meta, joursLocaux: document.days, prestations: document.itinerary, vouchers: voucherSummary }, 1); return normalizeBuiltItinerary(response); }
export function audit360(apiKey: string, model: string, document: TripDocument, voucherSummary: string, itinerary: BuiltItinerary | null, tickets: TicketItem[], notes: string, localFindings: LocalFinding[] = []) { return callJson<Audit360>(apiKey, model, auditSystem, { dossier: document.meta, itineraireDeReference: itinerary || document.days, prestationsExtension: document.itinerary, vouchers: voucherSummary, roadbook: document.roadbook, tickets, notes, controlesLocaux: localFindings }, 1); }
