import type { TicketItem, TripDocument } from "./tripcard";
import type { LocalFinding } from "./tripAudit";
const ENDPOINT = "https://openrouter.ai/api/v1/chat/completions"; const TRANSIENT = new Set([408, 429, 500, 502, 503, 504]);
export class OpenRouterError extends Error { constructor(public kind: "missing-key" | "invalid-key" | "overloaded" | "network" | "invalid-response", message: string) { super(message); this.name = "OpenRouterError"; } }
const extractJson = (content: string) => { const fenced = content.match(/```(?:json)?\s*([\s\S]*?)\s*```/i)?.[1] ?? content; const start = fenced.indexOf("{"); const end = fenced.lastIndexOf("}"); return JSON.parse(start >= 0 && end > start ? fenced.slice(start, end + 1) : fenced); };
async function callJson<T>(apiKey: string, model: string, system: string, user: unknown, maxRetries = 1): Promise<T> { if (!apiKey.trim()) throw new OpenRouterError("missing-key", "Renseigne une clé OpenRouter locale."); for (let attempt = 0; attempt <= maxRetries; attempt += 1) { if (attempt) await new Promise(resolve => setTimeout(resolve, Math.min(12000, 800 * 2 ** (attempt - 1)))); try { const response = await fetch(ENDPOINT, { method: "POST", headers: { "Content-Type": "application/json",
 Authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ model, messages: [{ role: "system", content: system }, { role: "user", content: JSON.stringify(user) }], response_format: { type: "json_object" }, temperature: 0.05, max_tokens: 4000 }) }); const payload = await response.json().catch(() => ({})) as { choices?: Array<{ message?: { content?: string } }>; error?: { message?: string } }; if (!response.ok) { if (TRANSIENT.has(response.status) && attempt < maxRetries) continue; throw new OpenRouterError(response.status === 401 || response.status === 403 ? "invalid-key" : TRANSIENT.has(response.status) ? "overloaded" : "network", payload.error?.message || `OpenRouter a répondu avec le statut ${response.status}.`); } const content = payload.choices?.[0]?.message?.content; if (!content) throw new OpenRouterError("invalid-response", "OpenRouter n’a renvoyé aucun JSON exploitable."); try { return extractJson(content) as T; } catch { throw new OpenRouterError("invalid-response", "La réponse OpenRouter n’est pas un JSON valide."); } } catch (error) { if (error instanceof OpenRouterError && (error.kind !== "network" || attempt >= maxRetries)) throw error; if (attempt >= maxRetries) throw new OpenRouterError("network", "La connexion à OpenRouter a échoué."); } } throw new OpenRouterError("network", "OpenRouter n’a pas pu être contacté."); }
const itinerarySystem = `Tu es un agent de voyage senior. Construis une seule fois l'itinéraire opérationnel jour par jour depuis les prestations fournies. Ne crée aucun événement qui ne soit pas dans les données fournies.

REGLE HEBERGEMENT : le meme hebergement est presque toujours mentionne dans PLUSIEURS sources a la fois (liste des hotels du voucher, carnet de voyage PDF, bandeau OnSpot) — CE SONT LES MEMES SEJOURS, jamais des sejours differents. Avant de renseigner les hebergements, identifie d'abord chaque sejour hotelier unique en croisant toutes les sources par nom d'hotel et ville, puis ne cree QU'UNE SEULE entree par sejour reel, avec les dates d'arrivee/depart les plus completes et coherentes trouvees entre les sources. Renseigne cet hebergement une seule fois dans le champ night du jour d'arrivee (title = nom de l'hotel, location = ville/adresse, notes = periode complete du sejour dans cet hotel du type "du 18 au 20 septembre"). Ne cree JAMAIS un evenement de type Hotel repete dans le tableau events pour chaque nuit intermediaire, et ne duplique JAMAIS un meme hebergement en plusieurs entrees night distinctes juste parce qu'il est mentionne dans plusieurs documents sources : les jours qui ne sont ni arrivee ni depart d'un hotel n'ont pas besoin de mentionner l'hebergement dans events.

REGLES DE CONTENU PAR TYPE D'EVENEMENT, à respecter strictement dans les champs title/subtitle/departure/arrival/notes :
- Vol : title contient le numéro de vol et le PNR ou code de réservation s'il existe (ex "V7 2236 · G4FEKY") ; departure et arrival contiennent les heures de départ et d'arrivée ; location le trajet aéroport à aéroport ; notes la compagnie et les détails bagages pertinents.
- Activité : title est le nom exact de l'activité ; subtitle le prestataire ou guide si connu ; notes une courte description si elle existe dans le texte source.
- Transfert : title est le nom du prestataire (ex "ARFEL TAXI") ; location le trajet lieu de départ vers lieu d'arrivée ; time l'heure de prise en charge.
- Location voiture : title le nom du loueur ; subtitle indique BSP, Flexible, ou "(non précisé)" si le statut n'est pas trouvé ; reference la référence de location ; location le lieu de prise en charge.
- Ferry : même principe que Transfert (prestataire, trajet, heure).

IGNORE STRICTEMENT tout ce qui releve du bandeau lateral ou des metadonnees generales et n'est PAS une prestation reservee : nom de l'agence, forfait/formule, plage de dates globale du sejour, liste des voyageurs, notes internes, reminders systeme, references de dossier, statuts de services (reconfirmation, eSIM). Une prestation reelle a toujours un prestataire ou nom commercial precis (compagnie aerienne, hotel, loueur, guide) associe a une date ou un horaire. Le titre ne doit jamais être seulement la catégorie générique de la prestation. Toutes les dates au format ISO strict YYYY-MM-DD, jamais DD/MM/YYYY ni texte libre. Donnée absente = (à vérifier), ne l'invente jamais. REGLE ANNEE PRIORITAIRE : si un document, voucher ou billet mentionne explicitement une année a 4 chiffres pour une date du sejour, cette annee prouvee prime TOUJOURS sur toute deduction ou supposition. Ne suppose jamais que le voyage a lieu l'annee suivante uniquement parce qu'un en-tete ne montre que jour et mois : cherche d'abord une annee explicite ailleurs dans les donnees fournies avant de deduire quoi que ce soit.

detectedTypes doit couvrir obligatoirement Vol, Hôtel, Activité, Transfert, Train, Location voiture, Ferry, même à 0 occurrence : quand count vaut 0, evidence doit être une phrase complète et directement affichable au format "Aucun/Aucune [type] identifié(e) dans les données fournies", jamais une phrase vague.

PERIMETRE STRICT : la construction d'itineraire ne compare JAMAIS l'itineraire aux vouchers ou au travel book, et ne signale AUCUNE incoherence entre sources dans le champ warnings — cette comparaison est le metier exclusif de l'analyse 360 realisee ensuite, separement. Le champ warnings sert uniquement a signaler une ambiguite interne a la construction elle-meme (ex: date impossible a determiner avec certitude), jamais une divergence avec un voucher. Chaque hebergement identifie dans les donnees fournies doit systematiquement apparaitre dans l'itineraire construit, sans exception : ne jamais omettre un hotel sous pretexte de simplification.

Réponds uniquement en JSON avec destination, period, travelers, days, undated et detectedTypes.`;
const auditSystem = `Tu es un agent de voyage senior et controleur qualite final d un voyage haut de gamme, avant depart. Tu as l oeil d un professionnel qui a vu des centaines de dossiers et qui sait precisement ou se cachent les erreurs couteuses. L itineraire fourni est deja la base de verite de travail : ne le reconstruis pas, ne produis pas un second itineraire, ne remplace aucune prestation.

GRILLE DE DETECTION SYSTEMATIQUE, a balayer entierement pour chaque dossier :
1. Coherence temporelle : chevauchements d horaires, trous de programme sur une journee entiere, nuit sans hebergement identifie, transfert programme avant l heure d arrivee du vol associe.
2. Coherence geographique : rupture de continuite entre deux lieux consecutifs sans transport identifie, transfert vers un lieu incoherent avec l etape suivante.
3. Coherence documentaire : prestation mentionnee dans l itineraire sans voucher correspondant ou l inverse, divergence de nom, date, heure ou lieu entre voucher, roadbook et itineraire.
4. Completude par type de prestation : vol sans PNR complet, hotel sans reference de reservation, activite ou transfert avec instruction de reconfirmation mais aucun rappel prevu.
5. Coherence voyageurs : nombre de places, chambres ou sieges reserves inferieur au nombre de voyageurs declare.
6. Documents d identite : presence ou absence signalee de passeport ou CNI par voyageur, jamais de jugement sur le contenu du document lui-meme.
7. Fil narratif des tickets : lis le CONTENU de chaque ticket (pas seulement son statut), identifie les incidents deja survenus (retard, no-show, erreur fournisseur), les reclamations ou reconfirmations EN COURS auprès d'un prestataire nomme, et croise ces informations avec les dates de l'itineraire. Si un ticket mentionne une action a realiser avant une date future de l'itineraire (reconfirmation, suivi de reclamation), cree une action orange precise citant le numero de ticket, le prestataire et la date concernee. Un incident deja resolu (rembourse, cause identifiee) devient un constat green factuel, pas une alerte.
8. Regimes alimentaires et allergies : lis attentivement la negation avant de signaler quoi que ce soit. Une mention explicite d'absence ("pas d'allergie", "aucune allergie signalee", "sans regime particulier") n'est JAMAIS une alerte, c'est une information rassurante a classer en green si mentionnee. Ne cree une alerte allergie/regime que si une allergie ou un regime est explicitement declare comme present.
8. Annee des dates : si les vouchers, billets ou documents mentionnent une annee explicite pour une date du sejour, cette annee prime toujours sur l'annee affichee dans l'itineraire de reference construit precedemment. Un ecart d'annee entre l'itineraire et un voucher n'est un vrai NO_GO que si le voucher ET une autre source independante confirment la meme annee differente ; sinon classe-le en orange a verifier, jamais en conflit critique automatique.

REGLES DE RIGUEUR IMPERATIVES :
- Ne qualifie jamais d incoherence une simple absence d information plausible mais non fournie : classe-la comme point a verifier avec l agence, pas comme anomalie.
- Ne signale un conflit que s il est objectivable et precisement citable avec les deux valeurs en cause.
- N invente jamais une anomalie pour remplir une categorie vide : un dossier propre doit produire une liste vide, pas une liste artificielle.
- Chaque mismatch doit donner la valeur de l itineraire, la valeur du voucher ou roadbook, la consequence metier concrete et la correction exacte a demander.
- Si une source est absente, cree une action obtenir la preuve plutot que de conclure que tout va bien.
- Utilise les controles locaux fournis comme indices de travail, jamais comme verite absolue a valider aveuglement.

Classe chaque resultat : red = critique, depart compromis, action immediate necessaire avec preuve a obtenir ; orange = a verifier ou action a planifier, avec responsable et echeance ; green = controle et conforme, avec preuve citee. Les suggestions ne doivent être produites que pour les jours qui ont un temps libre plausible ; jamais pour une arrivée tardive, un transit, un départ ou une journée déjà pleine. Donne une decision globale GO, GO_WITH_CHECKS ou NO_GO. Retourne uniquement ce JSON : {"status":"stable|attention|blocking","globalDecision":"GO|GO_WITH_CHECKS|NO_GO","confidence":0,"summary":"résumé précis","redItems":[{"code":"","title":"","detail":"","action":"","evidence":"","sourceRefs":[],"affectedServiceIds":[],"proofRequired":""}],"orangeItems":[{"code":"","title":"","detail":"","action":"","evidence":"","sourceRefs":[],"affectedServiceIds":[],"owner":"","proofRequired":""}],"greenChecks":[{"code":"","title":"","detail":"","evidence":"","sourceRefs":[]}],"duplicateCandidates":[],"dataReview":[],"crossSourceComparisons":[{"title":"","itineraryValue":"","voucherValue":"","roadbookValue":"","result":"match|mismatch|missing","action":""}],"actions":[{"priority":"red|orange|green","title":"","detail":"","owner":"","proofRequired":""}],"missingEvidence":[],"localRuleResults":[],"predepartureChecklist":[{"id":"","label":"","status":"ok|warning|critical|pending","finding":"","evidence":"","action":"","owner":"","timing":""}],"reminders":[{"type":"","date":"","action":"","source":""}],"suggestionsByDay":[{"dayIndex":0,"label":"","activities":[{"title":""}],"restaurants":[{"title":""}],"places":[{"title":""}]}],"internalNote":{"target":"Internal — OnSpot only","content":"","suggestions":[]}}. Français uniquement.`;
export type BuiltItinerary = { destination: string; period: string; travelers: Array<{ name: string; details?: string }>; days: Array<{ date: string; label: string; city?: string; night?: { title: string; location: string; notes: string } | null; events: Array<{ time: string; type: string; category?: string; title: string; subtitle?: string; location: string; departure?: string; arrival?: string; reference: string; notes: string; sourceRefs?: string[] }>; warnings?: string[] }>; undated: Array<{ type: string; title: string; notes: string; sourceRefs?: string[] }>; detectedTypes: Array<{ type: string; count: number; evidence: string }> };
export type AuditItem = { code: string; title: string; detail: string; action?: string; evidence?: string; sourceRefs?: string[]; affectedServiceIds?: string[]; owner?: string; proofRequired?: string; itineraryValue?: string; voucherValue?: string; roadbookValue?: string; result?: string };
export type Audit360 = { status: "stable" | "attention" | "blocking"; globalDecision: "GO" | "GO_WITH_CHECKS" | "NO_GO"; confidence: number; summary: string; description?: string; redItems: AuditItem[]; orangeItems: AuditItem[]; greenChecks: AuditItem[]; duplicateCandidates: AuditItem[]; dataReview: AuditItem[]; crossSourceComparisons: AuditItem[]; localRuleResults: AuditItem[]; missingEvidence: AuditItem[]; actions: Array<{ priority: string; title: string; detail: string; owner: string; proofRequired?: string }> ; predepartureChecklist?: Array<{ id: string; label: string; status: string; finding: string; evidence: string; action: string; owner: string; timing: string }>; reminders?: Array<{ type: string; date: string; action: string; source: string }>; suggestionsByDay?: Array<{ dayIndex: number; label: string; activities: Array<{ title: string }>; restaurants: Array<{ title: string }>; places: Array<{ title: string }> }>; internalNote?: { target: string; content: string; suggestions: string[] } };
export function buildLocalItinerary(document: TripDocument): BuiltItinerary { const byDay = document.days.map(day => ({ date: day.date, label: day.label, city: day.city, night: day.night ? { title: day.night.displayTitle, location: day.night.location, notes: day.night.notes } : null, events: day.events.map(item => ({ time: item.time, type: item.type, category: item.category, title: item.displayTitle, subtitle: item.subtitle, location: item.location, departure: item.departure, arrival: item.arrival, reference: item.reference, notes: item.notes, sourceRefs: item.sourceRefs })), warnings: day.warnings })); const dated = new Set(document.itinerary.flatMap(item => [item.id, ...item.nightCoverage])); const undated = document.itinerary.filter(item => !item.date).map(item => ({ type: item.type, title: item.displayTitle, notes: `${item.location || "Lieu à vérifier"} · ${item.notes || "Date à vérifier"}`, sourceRefs: item.sourceRefs })); return { destination: document.meta.destination, period: document.meta.period, travelers: document.meta.travelers.map(traveler => ({ name: String(traveler.name || traveler.fullName || "Voyageur") })), days: byDay, undated, detectedTypes: ["Vol", "Hôtel", "Activité", "Transfert", "Train", "Location voiture", "Ferry / bateau"].map(type => { const count = document.itinerary.filter(item => item.type === type).length; return { type, count, evidence: count ? "Prestation normalisée depuis le JSON extension" : `Aucun(e) ${type} identifié(e) dans les données fournies` }; }) }; }
function normalizeOutputDate(value: unknown) { const raw = String(value || "").trim(); const iso = raw.match(/^(20\d{2})-(\d{2})-(\d{2})/); if (iso) return `${iso[1]}-${iso[2]}-${iso[3]}`; const fr = raw.match(/^(\d{1,2})\/(\d{1,2})\/(20\d{2})$/); return fr ? `${fr[3]}-${fr[2].padStart(2, "0")}-${fr[1].padStart(2, "0")}` : ""; }
function dayLabel(date: string) { if (!date) return "Date à vérifier"; const parsed = new Date(`${date}T12:00:00Z`); return Number.isNaN(parsed.getTime()) ? "Date à vérifier" : parsed.toLocaleDateString("fr-FR", { day: "2-digit", month: "long" }); }
function normalizeBuiltItinerary(value: Partial<BuiltItinerary> | null | undefined): BuiltItinerary { const source = value || {}; const destination = String(source.destination || "Destination à vérifier"); return { destination, period: String(source.period || "Période à vérifier"), travelers: Array.isArray(source.travelers) ? source.travelers : [], days: Array.isArray(source.days) ? source.days.map(day => { const date = normalizeOutputDate(day?.date); return { ...day, date, label: date ? dayLabel(date) : String(day?.label || "Date à vérifier"), city: String(day?.city || destination), events: Array.isArray(day?.events) ? day.events : [], warnings: Array.isArray(day?.warnings) ? day.warnings : [] }; }) : [], undated: Array.isArray(source.undated) ? source.undated : [], detectedTypes: Array.isArray(source.detectedTypes) ? source.detectedTypes : [] }; }
export async function buildItinerary(apiKey: string, model: string, document: TripDocument, voucherSummary: string) { const response = await callJson<Partial<BuiltItinerary>>(apiKey, model, itinerarySystem, { donneesBrutesExtension: document.raw, vouchers: voucherSummary }, 1); return normalizeBuiltItinerary(response); }
export function audit360(apiKey: string, model: string, document: TripDocument, voucherSummary: string, itinerary: BuiltItinerary | null, tickets: TicketItem[], notes: string, localFindings: LocalFinding[] = []) { return callJson<Audit360>(apiKey, model, auditSystem, { dossier: document.meta, itineraireDeReference: itinerary || document.days, prestationsExtension: document.itinerary, vouchers: voucherSummary, roadbook: document.roadbook, tickets, notes, controlesLocaux: localFindings }, 1); }
