import type { TicketItem, TripDocument } from "./tripcard";
import type { LocalFinding } from "./tripAudit";
const ENDPOINT = "https://openrouter.ai/api/v1/chat/completions"; const TRANSIENT = new Set([408, 429, 500, 502, 503, 504]);
export class OpenRouterError extends Error { constructor(public kind: "missing-key" | "invalid-key" | "overloaded" | "network" | "invalid-response", message: string) { super(message); this.name = "OpenRouterError"; } }
const extractJson = (content: string) => { const fenced = content.match(/```(?:json)?\s*([\s\S]*?)\s*```/i)?.[1] ?? content; const start = fenced.indexOf("{"); const end = fenced.lastIndexOf("}"); return JSON.parse(start >= 0 && end > start ? fenced.slice(start, end + 1) : fenced); };
async function callJson<T>(apiKey: string, model: string, system: string, user: unknown, maxRetries = 1): Promise<T> { if (!apiKey.trim()) throw new OpenRouterError("missing-key", "Renseigne une clé OpenRouter locale."); for (let attempt = 0; attempt <= maxRetries; attempt += 1) { if (attempt) await new Promise(resolve => setTimeout(resolve, Math.min(12000, 800 * 2 ** (attempt - 1)))); try { const response = await fetch(ENDPOINT, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ model, messages: [{ role: "system", content: system }, { role: "user", content: JSON.stringify(user) }], response_format: { type: "json_object" }, temperature: 0.05 }) }); const payload = await response.json().catch(() => ({})) as { choices?: Array<{ message?: { content?: string } }>; error?: { message?: string } }; if (!response.ok) { if (TRANSIENT.has(response.status) && attempt < maxRetries) continue; throw new OpenRouterError(response.status === 401 || response.status === 403 ? "invalid-key" : TRANSIENT.has(response.status) ? "overloaded" : "network", payload.error?.message || `OpenRouter a répondu avec le statut ${response.status}.`); } const content = payload.choices?.[0]?.message?.content; if (!content) throw new OpenRouterError("invalid-response", "OpenRouter n’a renvoyé aucun JSON exploitable."); try { return extractJson(content) as T; } catch { throw new OpenRouterError("invalid-response", "La réponse OpenRouter n’est pas un JSON valide."); } } catch (error) { if (error instanceof OpenRouterError && (error.kind !== "network" || attempt >= maxRetries)) throw error; if (attempt >= maxRetries) throw new OpenRouterError("network", "La connexion à OpenRouter a échoué."); } } throw new OpenRouterError("network", "OpenRouter n’a pas pu être contacté."); }
const itinerarySystem = `Tu es un agent de voyage senior. Construis une seule fois l'itinéraire opérationnel jour par jour depuis les prestations fournies. Ne crée aucun événement. Le titre doit être le nom commercial de la prestation, jamais seulement sa catégorie. Ajoute subtitle pour la chambre, formule, classe ou détail, et category comme sous-information. Pour chaque date indique ville, hôtel de nuit, transports, transferts et activités. Donnée absente = (à vérifier). Réponds uniquement en JSON avec destination, period, travelers, days, undated et detectedTypes.`;
const auditSystem = `Tu es le contrôleur qualité final d'un voyage haut de gamme avant départ. L'itinéraire fourni est déjà la base de vérité de travail : NE LE RECONSTRUIS PAS, NE PRODUIS PAS UN SECOND ITINÉRAIRE ET NE REMPLACE AUCUNE PRESTATION. Ton unique mission est d'auditer tout le séjour et de dire précisément ce qui est conforme, ce qui ne va pas et quelle action réaliser.

Revue obligatoire : données apportées par l'extension ; doublons potentiels à supprimer ou modifier dans l'itinéraire ; couverture de chaque nuit et journée ; dates, horaires et villes ; transitions entre prestations ; voyageurs contre chambres/places ; références et preuves ; comparaison stricte vouchers, roadbook et itinéraire sur les noms, catégories, dates, horaires, lieux, chambres, voyageurs, références et statuts ; tickets ; instructions de reconfirmation ; boarding passes ; welcome call ; notes opérateur. Utilise aussi les contrôles locaux fournis. Pour toute divergence, affiche les deux valeurs observées. N'invente rien et écris à vérifier si la preuve manque.

Classe chaque résultat : red = critique ou risque de départ démontré, orange = action ou preuve à obtenir, green = contrôle réellement confirmé. Red doit avoir une action immédiate et une preuve. Orange doit avoir un responsable et une échéance ou condition. Green doit rester factuel. Donne une décision globale GO, GO_WITH_CHECKS ou NO_GO. Retourne uniquement ce JSON : {"status":"stable|attention|blocking","globalDecision":"GO|GO_WITH_CHECKS|NO_GO","confidence":0,"summary":"résumé précis","redItems":[{"code":"","title":"","detail":"","action":"","evidence":"","sourceRefs":[],"affectedServiceIds":[],"proofRequired":""}],"orangeItems":[{"code":"","title":"","detail":"","action":"","evidence":"","sourceRefs":[],"affectedServiceIds":[],"owner":"","proofRequired":""}],"greenChecks":[{"code":"","title":"","detail":"","evidence":"","sourceRefs":[]}],"duplicateCandidates":[],"dataReview":[],"crossSourceComparisons":[{"title":"","itineraryValue":"","voucherValue":"","roadbookValue":"","result":"match|mismatch|missing","action":""}],"actions":[{"priority":"red|orange|green","title":"","detail":"","owner":"","proofRequired":""}],"missingEvidence":[],"localRuleResults":[]}. Français uniquement.`;
export type BuiltItinerary = { destination: string; period: string; travelers: Array<{ name: string; details?: string }>; days: Array<{ date: string; label: string; city?: string; night?: { title: string; location: string; notes: string } | null; events: Array<{ time: string; type: string; category?: string; title: string; subtitle?: string; location: string; departure?: string; arrival?: string; reference: string; notes: string; sourceRefs?: string[] }>; warnings?: string[] }>; undated: Array<{ type: string; title: string; notes: string; sourceRefs?: string[] }>; detectedTypes: Array<{ type: string; count: number; evidence: string }> };
export type AuditItem = { code: string; title: string; detail: string; action?: string; evidence?: string; sourceRefs?: string[]; affectedServiceIds?: string[]; owner?: string; proofRequired?: string; itineraryValue?: string; voucherValue?: string; roadbookValue?: string; result?: string };
export type Audit360 = { status: "stable" | "attention" | "blocking"; globalDecision: "GO" | "GO_WITH_CHECKS" | "NO_GO"; confidence: number; summary: string; description?: string; redItems: AuditItem[]; orangeItems: AuditItem[]; greenChecks: AuditItem[]; duplicateCandidates: AuditItem[]; dataReview: AuditItem[]; crossSourceComparisons: AuditItem[]; localRuleResults: AuditItem[]; missingEvidence: AuditItem[]; actions: Array<{ priority: string; title: string; detail: string; owner: string; proofRequired?: string }> };
function normalizeBuiltItinerary(value: Partial<BuiltItinerary> | null | undefined): BuiltItinerary { const source = value || {}; return { destination: String(source.destination || "Destination à vérifier"), period: String(source.period || "Période à vérifier"), travelers: Array.isArray(source.travelers) ? source.travelers : [], days: Array.isArray(source.days) ? source.days.map(day => ({ ...day, date: String(day?.date || ""), label: String(day?.label || "Date à vérifier"), events: Array.isArray(day?.events) ? day.events : [], warnings: Array.isArray(day?.warnings) ? day.warnings : [] })) : [], undated: Array.isArray(source.undated) ? source.undated : [], detectedTypes: Array.isArray(source.detectedTypes) ? source.detectedTypes : [] }; }
export async function buildItinerary(apiKey: string, model: string, document: TripDocument, voucherSummary: string) { const response = await callJson<Partial<BuiltItinerary>>(apiKey, model, itinerarySystem, { dossier: document.meta, joursLocaux: document.days, prestations: document.itinerary, vouchers: voucherSummary }, 1); return normalizeBuiltItinerary(response); }
export function audit360(apiKey: string, model: string, document: TripDocument, voucherSummary: string, itinerary: BuiltItinerary | null, tickets: TicketItem[], notes: string, localFindings: LocalFinding[] = []) { return callJson<Audit360>(apiKey, model, auditSystem, { dossier: document.meta, itineraireDeReference: itinerary || document.days, prestationsExtension: document.itinerary, vouchers: voucherSummary, roadbook: document.roadbook, tickets, notes, controlesLocaux: localFindings }, 1); }
