import type { ItineraryItem, TripDocument, VoucherItem } from "./tripcard";
export type Reminder = { id: string; severity: "red" | "orange" | "green"; kind: "welcome-call" | "boarding-pass" | "reconfirmation" | "birthday"; when: string; title: string; detail: string; source: string; serviceId?: string; voucherId?: string };
const local = (date: string, time: string) => date && /^\d{4}-\d{2}-\d{2}$/.test(date) && /^\d{1,2}:\d{2}$/.test(time) ? `${date}T${time}:00` : "";
const valid = (value: Date) => !Number.isNaN(value.getTime());
const format = (value: Date) => valid(value) ? `${value.toISOString().slice(0, 10)} ${value.toTimeString().slice(0, 5)}` : "À calculer";
const minusHours = (date: string, time: string, hours: number) => { const value = new Date(`${date}T${time || "09:00"}:00`); if (!valid(value)) return "À calculer"; value.setHours(value.getHours() - hours); return format(value); };
const hasReconfirmation = (voucher: VoucherItem) => /reconfirm|re-confirm|24\s*h|24\s*hour|24h|veille|reconfirmation|reconfirmer/i.test(`${voucher.name} ${voucher.text}`);
const serviceReconfirmation = (item: ItineraryItem) => item.reconfirmationRequired || /reconfirm|re-confirm|24\s*h|24\s*hour|24h|veille|reconfirmation|reconfirmer/i.test(`${item.notes} ${JSON.stringify(item.raw)}`);
const birthdayHint = (document: TripDocument) => [...document.meta.profileNotes, document.notes, ...document.meta.travelers.flatMap(traveler => [traveler.birthday, traveler.birthDate, traveler.dateOfBirth, ...(Array.isArray(traveler.birthdayHints) ? traveler.birthdayHints : [])])].filter(Boolean).find(value => /anniversaire|birthday|date de naissance|birth date/i.test(String(value)) || /\b\d{1,2}[/-]\d{1,2}(?:[/-]\d{2,4})?\b/.test(String(value)));
export function buildReminders(document: TripDocument): Reminder[] {
  const reminders: Reminder[] = [];
  const flights = document.itinerary.filter(item => item.type === "Vol").sort((a, b) => `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));
  const arrivalFlight = flights.find(item => item.endTime && item.arrival) || flights[0];
  if (arrivalFlight?.date && arrivalFlight.endTime) {
    const arrival = new Date(local(arrivalFlight.date, arrivalFlight.endTime));
    if (valid(arrival)) { const due = new Date(arrival); due.setHours(due.getHours() + 5); if (due.getHours() >= 20) { due.setDate(due.getDate() + 1); due.setHours(9, 0, 0, 0); } reminders.push({ id: `welcome-${arrivalFlight.id}`, severity: "green", kind: "welcome-call", when: format(due), title: "Welcome call", detail: `Appeler les voyageurs 5 heures après l’arrivée à destination de ${arrivalFlight.displayTitle}. Si l’échéance dépasse 20:00, report automatique au lendemain à 09:00 heure locale.`, source: arrivalFlight.sourceRefs.join(", "), serviceId: arrivalFlight.id }); }
  } else reminders.push({ id: "welcome-missing", severity: "orange", kind: "welcome-call", when: "À calculer", title: "Welcome call à planifier", detail: "L’heure d’arrivée du premier vol à destination est absente ou non exploitable.", source: "Données extension" });
  for (const flight of flights) if (flight.date && flight.time) reminders.push({ id: `boarding-${flight.id}`, severity: "green", kind: "boarding-pass", when: minusHours(flight.date, flight.time, 24), title: "Check-in / boarding pass", detail: `Vérifier le check-in 24 heures avant le départ de l’aéroport : ${flight.displayTitle}. Vol : ${flight.title}. PNR : ${flight.reference || "à vérifier"}.`, source: flight.sourceRefs.join(", "), serviceId: flight.id }); else reminders.push({ id: `boarding-missing-${flight.id}`, severity: "orange", kind: "boarding-pass", when: "À calculer", title: "Boarding pass à planifier", detail: `${flight.displayTitle} ne contient pas d’heure de départ exploitable. Numéro de vol : ${flight.title || "à vérifier"}. PNR : ${flight.reference || "à vérifier"}.`, source: flight.sourceRefs.join(", "), serviceId: flight.id });
  for (const item of document.itinerary.filter(serviceReconfirmation)) if (item.date) reminders.push({ id: `reconfirm-service-${item.id}`, severity: "orange", kind: "reconfirmation", when: item.time ? minusHours(item.date, item.time, 24) : `${item.date} — 24h avant, heure à confirmer`, title: "Reconfirmation 24h avant", detail: `${item.displayTitle} demande une reconfirmation selon la source : ${item.reconfirmationEvidence || item.notes || "instruction détectée dans les données de la prestation"}.`, source: item.sourceRefs.join(", "), serviceId: item.id });
  for (const voucher of document.vouchers.filter(hasReconfirmation)) { const service = document.itinerary.find(item => voucher.linkedServiceIds.includes(item.id) || (item.title && voucher.text.toLowerCase().includes(item.title.toLowerCase().slice(0, 16)))); if (service && !serviceReconfirmation(service)) reminders.push({ id: `reconfirm-${voucher.id}`, severity: "orange", kind: "reconfirmation", when: service.time ? minusHours(service.date, service.time, 24) : `${service.date} — 24h avant, heure à confirmer`, title: "Reconfirmation 24h avant", detail: `${service.displayTitle} · instruction trouvée dans ${voucher.name} : ${voucher.text.slice(0, 260)}`, source: voucher.name, serviceId: service.id, voucherId: voucher.id }); else if (!service) reminders.push({ id: `reconfirm-unlinked-${voucher.id}`, severity: "orange", kind: "reconfirmation", when: "À rattacher", title: "Reconfirmation voucher non rattachée", detail: `Le voucher ${voucher.name} demande une reconfirmation mais la prestation correspondante reste à identifier.`, source: voucher.name, voucherId: voucher.id }); }
  const birthday = birthdayHint(document); if (birthday) reminders.push({ id: "birthday-detected", severity: "orange", kind: "birthday", when: "Date à confirmer", title: "Souhaiter un joyeux anniversaire", detail: `Une information d’anniversaire a été détectée dans le profil : ${String(birthday).slice(0, 240)}. Confirmer la date puis préparer le geste ou message client.`, source: "Profil voyageur / notes" });
  return reminders.sort((a, b) => a.when.localeCompare(b.when));
}

export type { ItineraryItem };
