import type { ItineraryItem, TripDocument, VoucherItem } from "./tripcard";
export type Reminder = { id: string; severity: "red" | "orange" | "green"; kind: "welcome-call" | "boarding-pass" | "reconfirmation" | "voucher"; when: string; title: string; detail: string; source: string; serviceId?: string; voucherId?: string };
const local = (date: string, time: string) => date && /^\d{4}-\d{2}-\d{2}$/.test(date) && /^\d{1,2}:\d{2}$/.test(time) ? `${date}T${time}:00` : "";
const valid = (value: Date) => !Number.isNaN(value.getTime());
const addHours = (value: string, hours: number) => { const date = new Date(value); if (!valid(date)) return "À calculer"; date.setHours(date.getHours() + hours); return valid(date) ? date.toISOString().slice(0, 16).replace("T", " ") : "À calculer"; };
const minusHours = (date: string, time: string, hours: number) => { const value = new Date(`${date}T${time || "09:00"}:00`); if (!valid(value)) return "À calculer"; value.setHours(value.getHours() - hours); return valid(value) ? value.toISOString().slice(0, 16).replace("T", " ") : "À calculer"; };
const hasReconfirmation = (voucher: VoucherItem) => /reconfirm|re-confirm|24\s*h|24\s*hour|24h|veille|reconfirmation/i.test(`${voucher.name} ${voucher.text}`);
export function buildReminders(document: TripDocument): Reminder[] {
  const reminders: Reminder[] = []; const flights = document.itinerary.filter(item => item.type === "Vol").sort((a, b) => `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));
  const destination = document.meta.destination.toLowerCase(); const arrivalFlight = flights.find(item => item.arrival && (item.arrival.toLowerCase().includes(destination.split(",")[0]) || item.city.toLowerCase().includes(destination.split(",")[0]))) || flights[0];
  if (arrivalFlight?.date && arrivalFlight.endTime) { const arrival = local(arrivalFlight.date, arrivalFlight.endTime); const candidate = new Date(arrival); if (valid(candidate)) { candidate.setHours(candidate.getHours() + 5); const when = candidate.getHours() >= 20 ? `${candidate.toISOString().slice(0, 10)} 09:00` : addHours(arrival, 5); reminders.push({ id: `welcome-${arrivalFlight.id}`, severity: "green", kind: "welcome-call", when, title: "Welcome call", detail: `Appeler les voyageurs 5 heures après l’arrivée de ${arrivalFlight.displayTitle}. Heure locale calculée à partir de l’arrivée ${arrivalFlight.endTime}.`, source: arrivalFlight.sourceRefs.join(", "), serviceId: arrivalFlight.id }); } else reminders.push({ id: "welcome-missing", severity: "orange", kind: "welcome-call", when: "À calculer", title: "Welcome call à planifier", detail: "La date ou l’heure d’arrivée du premier vol est invalide.", source: "Données extension" }); } else reminders.push({ id: "welcome-missing", severity: "orange", kind: "welcome-call", when: "À calculer", title: "Welcome call à planifier", detail: "Le premier vol d’arrivée à destination ou son heure d’arrivée n’est pas suffisamment renseigné.", source: "Données extension" });
  for (const flight of flights) if (flight.date && flight.time) reminders.push({ id: `boarding-${flight.id}`, severity: "green", kind: "boarding-pass", when: minusHours(flight.date, flight.time, 24), title: "Check-in / boarding pass", detail: `Récupérer ou vérifier le boarding pass 24 heures avant le départ de ${flight.displayTitle}.`, source: flight.sourceRefs.join(", "), serviceId: flight.id }); else reminders.push({ id: `boarding-missing-${flight.id}`, severity: "orange", kind: "boarding-pass", when: "À calculer", title: "Boarding pass à planifier", detail: `${flight.displayTitle} ne contient pas d’heure de départ exploitable.`, source: flight.sourceRefs.join(", "), serviceId: flight.id });
  for (const voucher of document.vouchers) if (hasReconfirmation(voucher)) { const service = document.itinerary.find(item => voucher.linkedServiceIds.includes(item.id) || voucher.text.toLowerCase().includes(item.title.toLowerCase().slice(0, 16))); if (service?.date) reminders.push({ id: `reconfirm-${voucher.id}`, severity: "orange", kind: "reconfirmation", when: service.time ? minusHours(service.date, service.time, 24) : `${service.date} — 24h avant, heure à confirmer`, title: "Reconfirmation 24h avant", detail: `${service.displayTitle} · extrait : ${voucher.text.slice(0, 260)}`, source: voucher.name, serviceId: service.id, voucherId: voucher.id }); else reminders.push({ id: `reconfirm-unlinked-${voucher.id}`, severity: "orange", kind: "reconfirmation", when: "À rattacher", title: "Reconfirmation voucher non rattachée", detail: `Le voucher ${voucher.name} demande une reconfirmation mais sa prestation n’est pas identifiée.`, source: voucher.name, voucherId: voucher.id }); }
  for (const voucher of document.vouchers.filter(item => !item.linkedServiceIds.length)) reminders.push({ id: `voucher-${voucher.id}`, severity: "orange", kind: "voucher", when: "À contrôler", title: "Voucher à comparer", detail: `${voucher.name} n’est pas rattaché automatiquement à une prestation de l’itinéraire.`, source: voucher.name, voucherId: voucher.id });
  return reminders.sort((a, b) => a.when.localeCompare(b.when));
}
