import type { AnyRecord, ItineraryItem, TripDocument } from "./tripcard";

export type AuditSeverity = "red" | "orange" | "green";
export type LocalFinding = { severity: AuditSeverity; code: string; title: string; detail: string; action: string; evidence: string; sourceRefs: string[]; affectedServiceIds: string[]; owner?: string; proofRequired?: string };
const finding = (severity: AuditSeverity, code: string, title: string, detail: string, action: string, evidence: string, items: ItineraryItem[] = [], proofRequired = ""): LocalFinding => ({ severity, code, title, detail, action, evidence, sourceRefs: Array.from(new Set(items.flatMap(i => i.sourceRefs))), affectedServiceIds: items.map(i => i.id), proofRequired });
const num = (value: unknown) => { const match = String(value ?? "").match(/\d+/); return match ? Number(match[0]) : 0; };
const values = (item: ItineraryItem) => `${item.title} ${item.subtitle} ${item.notes} ${JSON.stringify(item.raw)}`;
const formatRange = (dates: string[]) => { if (!dates.length) return ""; const sorted = [...new Set(dates)].sort(); const ranges: string[] = []; let start = sorted[0]; let previous = sorted[0]; for (const current of sorted.slice(1)) { const expected = new Date(`${previous}T12:00:00Z`); expected.setUTCDate(expected.getUTCDate() + 1); const next = expected.toISOString().slice(0, 10); if (current !== next) { ranges.push(start === previous ? start : `${start} → ${previous}`); start = current; } previous = current; } ranges.push(start === previous ? start : `${start} → ${previous}`); return ranges.join(", "); };
const fr = (value: string) => { const match = value.match(/^(\d{4})-(\d{2})-(\d{2})$/); return match ? `${match[3]}/${match[2]}/${match[1]}` : value; };

export function runLocalAudit(document: TripDocument): LocalFinding[] {
  const output: LocalFinding[] = [];
  const seen = new Map<string, ItineraryItem[]>();
  for (const item of document.itinerary) { if (!item.duplicateKey || item.title === "Prestation sans titre") continue; const bucket = seen.get(item.duplicateKey) || []; bucket.push(item); seen.set(item.duplicateKey, bucket); }
  for (const items of seen.values()) if (items.length > 1) output.push(finding("orange", "DUPLICATE_CANDIDATE", "Doublon potentiel dans l’itinéraire", `${items.map(i => `${i.displayTitle} (${i.reference || "sans référence"})`).join(" / ")} semblent partager le même type, la même date et le même lieu.`, "Comparer les références et supprimer ou fusionner la prestation en trop.", items.map(i => `${i.date} · ${i.location} · ${i.reference || "référence absente"}`).join(" | "), items, "Réservation fournisseur ou confirmation de la prestation conservée"));
  const emptyDates = document.days.filter(day => day.empty).map(day => day.date);
  const missingNightDates = document.days.filter(day => !day.night).map(day => day.date);
  if (emptyDates.length) output.push(finding("orange", "EMPTY_PERIOD", "Période sans prestation identifiable", `Du ${fr(emptyDates[0])}${emptyDates.length > 1 ? ` au ${fr(emptyDates[emptyDates.length - 1])}` : ""}, aucune prestation exploitable n’est rattachée au séjour. Cette période doit être comparée au roadbook et aux vouchers.`, "Vérifier les nuits, transports et activités de cette période puis rattacher les éléments manquants.", `Dates concernées : ${formatRange(emptyDates).replace(/\d{4}-\d{2}-\d{2}/g, fr)}`, [], "Roadbook, voucher ou confirmation fournisseur couvrant la période"));
  if (missingNightDates.length) output.push(finding("orange", "MISSING_NIGHT_PERIOD", "Nuits non couvertes", `Les nuits du ${fr(missingNightDates[0])}${missingNightDates.length > 1 ? ` au ${fr(missingNightDates[missingNightDates.length - 1])}` : ""} ne sont pas couvertes par un hébergement identifié.`, "Contrôler les dates de check-in/check-out et rechercher le voucher hôtel correspondant.", `Dates concernées : ${formatRange(missingNightDates).replace(/\d{4}-\d{2}-\d{2}/g, fr)}`, [], "Voucher hôtel ou confirmation d’hébergement"));
  for (const day of document.days) {
    const timed = day.events.filter(item => item.time).sort((a, b) => a.time.localeCompare(b.time));
    for (let index = 1; index < timed.length; index += 1) if (timed[index].time === timed[index - 1].time) output.push(finding("red", "TIME_OVERLAP", "Chevauchement horaire critique", `${timed[index - 1].displayTitle} et ${timed[index].displayTitle} commencent tous deux à ${timed[index].time}.`, "Confirmer l’horaire exact et modifier l’itinéraire ou la réservation en conflit.", `${timed[index - 1].id} / ${timed[index].id}`, [timed[index - 1], timed[index]], "Deux confirmations ou horaires fournisseur comparables"));
  }
  for (const item of document.itinerary) {
    const raw = values(item); if (!item.reference && !item.hasProof) output.push(finding("orange", "MISSING_PROOF", "Preuve de réservation absente", `${item.displayTitle} n’a ni référence ni voucher rattaché.`, "Rattacher le voucher ou demander la confirmation fournisseur.", `${item.date} · ${item.displayTitle}`, [item], "Voucher, PNR ou numéro de confirmation"));
    if (item.reconfirmationRequired) output.push(finding("orange", "RECONFIRMATION", "Reconfirmation demandée par la source", `${item.displayTitle} contient une instruction de reconfirmation : ${item.reconfirmationEvidence}`, "Créer ou traiter le rappel de reconfirmation 24 heures avant la prestation.", item.reconfirmationEvidence, [item]));
    const capacity = num(item.raw.rooms || item.raw.roomCount || item.raw.passengers || item.raw.guests || item.raw.participants); if (capacity && document.meta.travelers.length && capacity < document.meta.travelers.length && /hôtel|vol|train|activité/i.test(item.type)) output.push(finding("red", "CAPACITY_MISMATCH", "Capacité inférieure au nombre de voyageurs", `${item.displayTitle} indique ${capacity} place(s)/participant(s) pour ${document.meta.travelers.length} voyageur(s).`, "Confirmer la capacité et corriger la réservation si nécessaire.", raw.slice(0, 300), [item], "Confirmation avec capacité corrigée"));
  }
  const corpus = `${document.rawText}\n${document.notes}\n${document.roadbook}\n${document.vouchers.map(voucher => `${voucher.name}\n${voucher.category}\n${voucher.text}`).join("\n")}`;
  const flights = document.itinerary.filter(item => item.type === "Vol");
  const activities = document.itinerary.filter(item => item.type === "Activité");
  const hasPhone = /(?:téléphone|telephone|mobile|portable|phone|whatsapp|tel\.?)\s*[:：+\d()[\].\/-]{7,}/i.test(corpus);
  const emails = corpus.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g) || [];
  const hasClientEmail = emails.some(email => !/(?:agence|agency|onspot)/i.test(corpus.slice(Math.max(0, corpus.indexOf(email) - 100), corpus.indexOf(email) + email.length + 100)));
  const hasPnr = flights.length > 0 && flights.every(item => Boolean(item.reference) || /\bPNR\b|booking reference|record locator|référence de réservation/i.test(values(item)));
  const hasIdentity = document.vouchers.some(voucher => /identity|passeport|passport|cni|carte nationale/i.test(`${voucher.name} ${voucher.category} ${voucher.text}`));
  const hasArrival = flights.some(item => Boolean(item.raw.arrivalDate || item.raw.arrival || item.arrival) && Boolean(item.raw.arrivalTime || item.raw.arrivalTimeLocal));
  const hasReturn = flights.length > 1 || /retour|return|flight back/i.test(corpus);
  const addOperational = (code: string, title: string, detail: string, action: string, evidence: string, severity: AuditSeverity = "orange") => output.push(finding(severity, code, title, detail, action, evidence, [], "Preuve documentaire ou confirmation agence"));
  if (!document.meta.profileNotes.some(note => /note|instruction|vip|exigeant|allerg|mobilité/i.test(note)) && !/note|instruction|agency notes/i.test(corpus)) addOperational("AGENCY_NOTES_REVIEW", "Notes agence non retrouvées", "Les notes agence ne sont pas identifiables dans l’export.", "Lire les notes agence dans OnSpot avant de reconfirmer le dossier.", "Aucune note agence structurée détectée.");
  if (!hasPhone) addOperational("CLIENT_PHONE_MISSING", "Téléphone client non prouvé", "Aucun numéro direct du client n’est identifiable avec certitude.", "Demander le téléphone direct du client à l’agence.", "Aucun champ téléphone exploitable dans les métadonnées, notes ou vouchers.");
  if (!hasClientEmail) addOperational("CLIENT_EMAIL_MISSING", "Email client distinct de l’agence non prouvé", "Aucun email direct du client n’est distingué d’une éventuelle adresse agence.", "Demander l’email client et exclure l’adresse de l’agence.", emails.length ? `Email(s) détecté(s), mais aucun n’est prouvé comme adresse client : ${emails.join(" · ")}.` : "Aucun email détecté.");
  if (flights.length && !hasPnr) addOperational("FLIGHT_PNR_MISSING", "PNR absent pour au moins un vol", "Les segments aériens ne disposent pas tous d’un PNR ou d’une référence exploitable.", "Obtenir le billet ou plan de vol avec PNR visible pour chaque segment.", flights.map(item => `${item.displayTitle} · ${item.reference || "PNR absent"}`).join(" | "), "red");
  if (!hasIdentity) addOperational("PASSPORT_PROOF_MISSING", "Passeports / CNI non prouvés", "Aucun voucher ou document d’identité identifiable n’est rattaché à l’export.", "Demander les passeports/CNI et vérifier les pièces jointes par voyageur.", "Les mentions textuelles seules ne sont pas considérées comme preuve.");
  if (flights.length && !hasArrival) addOperational("ARRIVAL_DETAILS_MISSING", "Arrivée incomplète", "La date, l’heure et la ville d’arrivée ne sont pas toutes exploitables.", "Compléter le segment d’arrivée avant de programmer le Welcome Call.", flights.map(item => `${item.displayTitle} · ${item.date} · ${item.location}`).join(" | "), "red");
  if (flights.length && !hasReturn) addOperational("RETURN_DETAILS_MISSING", "Retour non identifié", "Le segment retour ou sa date ne sont pas clairement identifiables.", "Confirmer le vol retour et programmer le Good Bye Call à J-2.", "Aucun retour explicite détecté dans les vols, tickets ou vouchers.");
  if (activities.length) {
    const missingDetails = activities.filter(item => !/\d{1,2}:\d{2}/.test(values(item)) || !/(?:\+?\d[\d ().\/-]{7,}|@)/.test(values(item)) || !item.location || /à vérifier/i.test(item.location));
    if (missingDetails.length) addOperational("ACTIVITY_VOUCHER_DETAILS", "Détails de rendez-vous activité incomplets", `${missingDetails.length} activité(s) n’exposent pas clairement adresse, heure et contact local.`, "Contrôler chaque voucher activité et compléter adresse de rendez-vous, heure et coordonnées du prestataire.", missingDetails.map(item => item.displayTitle).join(" · "));
  }
  if (!document.roadbook && document.itinerary.length) addOperational("ROADBOOK_MIRROR_MISSING", "Carnet de voyage non retrouvé", "La chronologie ne peut pas encore être comparée au carnet de voyage miroir des vouchers.", "Récupérer le roadbook et comparer les dates, horaires, lieux et références.", "document.roadbook est vide.");
  if (!/internal\s*[—-]\s*onspot|onspot only|note jaune/i.test(corpus)) addOperational("INTERNAL_NOTE_REQUIRED", "Note interne OnSpot à préparer", "Aucun espace Internal — OnSpot only exploitable n’est détecté dans l’export.", "Ajouter les points de vigilance, décisions et contacts dans la note interne non visible par l’agence.", "Cible attendue : Internal — OnSpot only.");
  if (!/anniversaire|birthday|date de naissance|birth date/i.test(corpus)) addOperational("BIRTHDAY_REVIEW", "Anniversaire non vérifiable", "Aucune date de naissance ou mention d’anniversaire n’est disponible pour contrôle.", "Vérifier les passeports et le profil voyageurs, puis créer un rappel uniquement si la date est prouvée.", "Aucune information anniversaire détectée.");
  if (!output.length) output.push(finding("green", "LOCAL_CHECKS_CLEAR", "Contrôles locaux sans anomalie", "Aucun conflit déterministe n’a été trouvé dans les données importées.", "Poursuivre la revue des preuves et des règles métier.", "JSON, prestations et projection locale"));
  return output;
}

export function auditCounts(findings: LocalFinding[]) { return { red: findings.filter(item => item.severity === "red").length, orange: findings.filter(item => item.severity === "orange").length, green: findings.filter(item => item.severity === "green").length }; }
export function findingToAi(item: LocalFinding) { return { ...item }; }
